name: lakost_app
description: laKost - Platform pencarian kost modern dan terpercaya.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animations: ^2.0.11
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1

  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  flutter_map: ^6.1.0 # Versi terbaru untuk Leaflet di Flutter
  latlong2: ^0.9.1
  intl: ^0.19.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/house_bg.png

